=== SMart-337/National-Parks/NationalParks.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" 
attributeFormDefault="unqualified"> 
<xsd:element name="NationalParks" type="NationalParksType" />
<xsd:complexType name="NationalParksType">
    <xsd:sequence>
        <xsd:element name="NationalPark" type="NationalParkDetails" minOccurs="1" maxOccurs="unbounded" />
</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="NationalParkDetails">
    <xsd:element name="Name" type="xsd:string" minOccurs="1" maxOccurs="1" />
    <xsd:element name="Phone" type="PhoneType" minOccurs="1" maxOccurs="1" />
    <xsd:element name="Address" type="AddressDetails" minOccurs="1" maxOccurs="unbounded" />
</xsd:complexType >
    <xsd:attribute name="Rating" type="xsd:decimal" use="optional" />
    <xsd:complexType name="AddressDetails">
        <xsd:sequence>
            <xsd:element name="Number" type="NumberType" minOccurs="1" maxOccurs="unbounded" />
            <xsd:element name="Street" type="xsd:string" minOccurs="1" maxOccurs="1" />
            <xsd:element name="City" type="xsd:string" minOccurs="1" maxOccurs="1" />
            <xsd:element name="State" type="xsd:string" minOccurs="1" maxOccurs="1" />
            <xsd:element name="Zip" type="xsd:string" minOccurs="1" maxOccurs="1" />
</xsd:sequence>
<xsd:complexType name="NumberType">
    <xsd:restriction base="xsd:string">
    <xsd:pattern value="\d{3}\-\d{3} \d{4}"/>
</xsd:restriction>
</xsd:complexType>
</xsd:schema>

=== SMart-337/National-Parks/NationalParksError.xml
<?xml version="1.0" encoding="UTF-8"?> 
<NationalParks xmlns="https://smart-337.github.io" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://smart-337.github.io https://smart-337.github.io/NationalParks.xsd" >
<NationalPark>
    <Name>
        Alcatraz Island
    </Name>
    <Address NearestAirport="San Francisco">
        <Number>Alcatraz Island</Number>
        <Street>Alcatraz Island</Street>
        <City>San Francisco</City>
        <State>CA</State>
        <Zip>94133</Zip>
    </Address>
</NationalPark>
<NationalPark Rating="4.8">
    <Name>Zion National Park</Name>
    <Phone>437-772-3256</Phone>
    <Address NearestAirport="St. George Regional">
        <Number>1</Number>
        <Street>Zion Park Blvd</Street>
        <City>Springdale</City>
        <State>UT</State>
        <Zip>84767</Zip>
    </Address>
</NationalPark>
<NationalPark>
    <Name>Seqouia &amp; Kings Canyon</Name>
    <Phone>559-565-3341</Phone>
    <Address NearestAirport="WoodLake Airport">
        <Number>47050</Number>
        <Street>Generals Highway</Street>
        <City>Three Rivers</City>
        <State>CA</State>
        <Zip>93271</Zip>
    </Address>
</NationalPark>
</NationalParks>
